<html>
	<a href="memorial.php">Continue</a>
</html>

In this page, we will have the users select all the types of information they would like to include in the memorial:
-Grace: Do you need variables to store the different categories or another option?
-Users select what they want to include from their own and their collaborators.
-Obtain all public data from Facebook (Marie).
-Data gets sent through meaning.php.