<html>
	<a href="profile.php">Account</a>
	<a href="editCoverPic.php">Edit Cover Picture</a>
	<a href="editDeadInfo.php">Edit Grace's Profile</a>
	<a href="editFavorites.php">Edit Favorites</a>
	<a href="editPhotos.php">Edit Photos</a>
	<a href="editPost.php">Edit Posts</a>
	<a href="editProfilePhoto.php">Edit Profile Picture</a>
	<a href="editVideos.php">Edit Videos</a>
</html>

Default memorial right after the meaning maker. User can make edits here.