<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="../Stylesheets/bootstrap.css" media="screen">
		<link rel="stylesheet" href="../Stylesheets/font-awesome.min.css">
		<link rel="stylesheet" href="../Stylesheets/bootswatch.min.css">
		<link rel="stylesheet" href="../Stylesheets/profile_style.css">
		<link rel="stylesheet" href="../Stylesheets/style.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="../Scripts/bsa.js"></script>
		<div id="fb-root"></div>
		<!-- Javascript SDK for Facebook-->
		<script>
			window.fbAsyncInit = function() {
				// init the FB JS SDK
				FB.init({
					appId : '665113106856066', // App ID from the app dashboard
					status : true, // Check Facebook Login status
					xfbml : true // Look for social plugins on the page
				});

				// Additional initialization code such as adding Event Listeners goes here
			};

			// Load the SDK asynchronously
			( function() {
					// If we've already installed the SDK, we're done
					if (document.getElementById('facebook-jssdk')) {
						return;
					}

					// Get the first script element, which we'll use to find the parent node
					var firstScriptElement = document.getElementsByTagName('script')[0];

					// Create a new script element and set its id
					var facebookJS = document.createElement('script');
					facebookJS.id = 'facebook-jssdk';

					// Set the new script's source to the source of the Facebook JS SDK
					facebookJS.src = '//connect.facebook.net/en_US/all.js';

					// Insert the Facebook JS SDK into the DOM
					firstScriptElement.parentNode.insertBefore(facebookJS, firstScriptElement);
				}());
		</script>

		<div id="fb-root"></div>
		<script>
			( function(d, s, id) {
					var js, fjs = d.getElementsByTagName(s)[0];
					if (d.getElementById(id))
						return;
					js = d.createElement(s);
					js.id = id;
					js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
					fjs.parentNode.insertBefore(js, fjs);
				}(document, 'script', 'facebook-jssdk'));
		</script>

		<div class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand" href="profile.phtml"><img src="../Images/logo.png"></a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="profile.phtml">Profile</a>
					</li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div><!-- /.navbar -->
		<div class="fb-send" data-href="http://developers.facebook.com/docs/plugins/" data-colorscheme="light"></div>
		<button type="button" class="btn btn-primary btn-lg">
			Add New Collaborator
		</button>

		<script src="../Scripts/jquery.min.js"></script>
		<script src="../Scripts/bootstrap.min.js"></script>
		<script src="../Scripts/bootswatch.js"></script>
	</body>
</html>