<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="../Stylesheets/bootstrap.css" media="screen">
		<link rel="stylesheet" href="../Stylesheets/font-awesome.min.css">
		<link rel="stylesheet" href="../Stylesheets/bootswatch.min.css">
		<link rel="stylesheet" href="../Stylesheets/style.css">
		<link rel="stylesheet" href="../Stylesheets/login_style.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="../Scripts/bsa.js"></script>

		<div class="jumbotron">
			<img src="../Images/login.png">
			<p id="fb_button">
				<a href="profile.phtml" class="btn btn-primary btn-lg"><img id="fb_logo" src="../Images/fb_logo.png"> Sign in with Facebook</a>
			</p>
		</div>

		<footer>
			<div class="col-lg-12">
				<p>
					Made by Team Digital Afterlife.
				</p>
				<p>
					Based on <a href="http://getbootstrap.com">Bootstrap</a>. Web fonts from <a href="http://www.google.com/webfonts">Google</a>.
				</p>
			</div>
		</footer>

		<script src="../Scripts/jquery.min.js"></script>
		<script src="../Scripts/bootstrap.min.js"></script>
		<script src="../Scripts/bootswatch.js"></script>
	</body>
</html>