<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="../Stylesheets/bootstrap.css" media="screen">
		<link rel="stylesheet" href="../Stylesheets/font-awesome.min.css">
		<link rel="stylesheet" href="../Stylesheets/bootswatch.min.css">
		<link rel="stylesheet" href="../Stylesheets/profile_style.css">
		<link rel="stylesheet" href="../Stylesheets/memorial.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="../Scripts/bsa.js"></script>

		<div class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand" href="profile.phtml"><img src="../Images/logo.png"></a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<a href="profile.phtml">Profile</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="#memorials">Memorials</a>
							</li>
							<li>
								<a href="#invitations">Invitations</a>
							</li>
							<li>
								<a href="#finalizedMemorials">Finalized Memorials</a>
							</li>
						</ul>
					</li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div><!-- /.navbar -->

		<div class="jumbotron">
			<div id="deceased_info">
				<div id="info_picture"><img src="../Images/profile.jpg"></div>
				<div id="info_content">
					<h3>In memory of Grace Yun-Ting Pai</h3>
					<h4>08/28/1992 - 10/20/2013</h4>
					<h4>Beloved sister and friend</h4>
				</div>
			</div>
		</div><hr>
	
		<div class="jumbotron">
			<div id="coverPicture">
				<span><img src="../Images/collage.jpg"></span>
			</div>
		</div>

		<div class="jumbotron">
			<div id="sections">
				<a class= "section" id= "section_posts"><img src="../Images/posts.png"></a>
				<a class= "section" id= "section_photos"><img src="../Images/photos.png"></a>
				<a class= "section" id= "section_favorties"><img src="../Images/favorites.png"></a>
				<a class= "section" id= "section_videos"><img src="../Images/videos.png"></a>
			</div>
			<div id="story">
				
			</div>
		</div>
		<hr>

		<script src="../Scripts/jquery.min.js"></script>
		<script src="../Scripts/bootstrap.min.js"></script>
		<script src="../Scripts/bootswatch.js"></script>
	</body>
</html>