<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="../Stylesheets/bootstrap.css" media="screen">
		<link rel="stylesheet" href="../Stylesheets/font-awesome.min.css">
		<link rel="stylesheet" href="../Stylesheets/bootswatch.min.css">
		<link rel="stylesheet" href="../Stylesheets/profile_style.css">
		<link rel="stylesheet" href="../Stylesheets/style.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="../Scripts/bsa.js"></script>

		<div class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand" href="#"><img src="../Images/logo.png"></a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<a href="#">Profile</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="#Projects">Projects</a>
							</li>
							<li>
								<a href="#Invitations">Invitations</a>
							</li>
							<li>
								<a href="#PastProjects">Past Projects</a>
							</li>
						</ul>
					</li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div><!-- /.navbar -->

		<div class="bs-example">
			<ul class="nav nav-tabs" style="margin-bottom: 15px;">
				<li class="active">
					<a href="#Projects" data-toggle="tab">Projects</a>
				</li>
				<li>
					<a href="#Invitations" data-toggle="tab">Invitations</a>
				</li>
				<li>
					<a href="#PastProjects" data-toggle="tab">Past Projects</a>
				</li>
			</ul>
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane fade active in" id="Projects">
					<p>
						Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.
					</p>
				</div>
				<div class="tab-pane fade" id="Invitations">
					<p>
						Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit.
					</p>
				</div>
				<div class="tab-pane fade" id="PastProjects">
					<p>
						Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork.
					</p>
				</div>
			</div>
		</div>

		<footer>
			<div class="col-lg-12">
				<p>
					Made by Team Digital Afterlife.
				</p>
				<p>
					Based on <a href="http://getbootstrap.com">Bootstrap</a>. Web fonts from <a href="http://www.google.com/webfonts">Google</a>.
				</p>
			</div>
		</footer>

		<script src="../Scripts/jquery.min.js"></script>
		<script src="../Scripts/bootstrap.min.js"></script>
		<script src="../Scripts/bootswatch.js"></script>
	</body>
</html>