<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="../Stylesheets/bootstrap.css" media="screen">
		<link rel="stylesheet" href="../Stylesheets/font-awesome.min.css">
		<link rel="stylesheet" href="../Stylesheets/bootswatch.min.css">
		<link rel="stylesheet" href="../Stylesheets/profile_style.css">
		<link rel="stylesheet" href="../Stylesheets/style.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="../Scripts/bsa.js"></script>

		<div class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand" href="#"><img src="../Images/logo.png"></a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Home <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li>
								<a href="#">Profile</a>
							</li>
							<li class="divider"></li>
							<li>
								<a href="#">Memorials</a>
							</li>
							<li>
								<a href="#invitations">Invitations</a>
							</li>
							<li>
								<a href="#finalizedMemorials">Finalized Memorials</a>
							</li>
						</ul>
					</li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div><!-- /.navbar -->

		<div class="bs-example">
			<ul class="nav nav-tabs" style="margin-bottom: 15px;">
				<li class="active">
					<a href="#memorials" data-toggle="tab">Memorials</a>
				</li>
				<li>
					<a href="#invitations" data-toggle="tab">Invitations</a>
				</li>
				<li>
					<a href="#finalizedMemorials" data-toggle="tab">Finalized Memorials</a>
				</li>
			</ul>
			<div id="myTabContent" class="tab-content">
				<div class="tab-pane fade active in" id="memorials">
					<button onclick="location.href='create_info.phtml'"type="button" class="btn btn-primary btn-lg">
						Create New Memorial
					</button>

					<button onclick="location.href='memorial.phtml'" type="button" class="btn btn-default btn-lg btn-block">
						Grace Pai's Memorial
					</button>
					<div class="btn-group btn-group-justified">
						<a href="memorial.phtml" class="btn btn-default">Edit</a>
						<a href="collaborators.phtml" class="btn btn-default">Collaborators</a>
						<a href="finalize_info.phtml" class="btn btn-default">Finalize</a>
						<a href="#" class="btn btn-default">Delete</a>
					</div>

					<button type="button" class="btn btn-default btn-lg btn-block">
						Jane Doe's Memorial
					</button>
					<div class="btn-group btn-group-justified">
						<a href="memorial.phtml" class="btn btn-default">Edit</a>
						<a href="collaborators.phtml" class="btn btn-default">Collaborators</a>
						<a href="finalize_info.phtml" class="btn btn-default">Finalize</a>
						<a href="#" class="btn btn-default">Delete</a>
					</div>
					<!--<center>
					<h2> You currently have no active memorials. </h2>
					</center> -->
				</div>
				<div class="tab-pane fade" id="invitations">
					<button type="button" class="btn btn-primary btn-lg">
						Add New Collaborator
					</button>

					<div class="bs-docs-section">
						<div class="row">
							<div class="col-lg-12">
								<div class="bs-example table-responsive">
									<table class="table table-striped table-bordered table-hover">
										<thead>
											<tr>
												<th>#</th>
												<th>Column heading</th>
												<th>Column heading</th>
												<th>Column heading</th>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>1</td>
												<td>Column content</td>
												<td>Column content</td>
												<td>Column content</td>
											</tr>
											<tr>
												<td>2</td>
												<td>Column content</td>
												<td>Column content</td>
												<td>Column content</td>
											</tr>

										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
				</div>

				<div class="tab-pane fade" id="finalizedMemorials">
					<button onclick="location.href='memorial.phtml'" type="button" class="btn btn-default btn-lg btn-block">
						Amy Williams's Memorial
					</button>
					<div class="btn-group btn-group-justified">
						<a href="#" class="btn btn-default">View</a>
						<a href="#" class="btn btn-default">Download web package</a>
					</div>

					</div>
				</div>
			</div>

			<script src="../Scripts/jquery.min.js"></script>
			<script src="../Scripts/bootstrap.min.js"></script>
			<script src="../Scripts/bootswatch.js"></script>
	</body>
</html>