<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="../Stylesheets/bootstrap.css" media="screen">
		<link rel="stylesheet" href="../Stylesheets/font-awesome.min.css">
		<link rel="stylesheet" href="../Stylesheets/bootswatch.min.css">
		<link rel="stylesheet" href="../Stylesheets/profile_style.css">
		<link rel="stylesheet" href="../Stylesheets/create_memorial.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="../Scripts/bsa.js"></script>

				<div class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand" href="profile.phtml"><img src="../Images/logo.png"></a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="profile.phtml">Profile</a>
					</li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div><!-- /.navbar -->

		<div class="jumbotron">
			<div id="container">
				<div id="image">
					<img src= "../Images/anonymous.jpg">
				</div>
				<div id="content">
					<h4>Name of the Deceased:
					<input class="form-control" id="focusedInput" type="text" >
					</h4></br>

					<h4>Date of Death:
					<input type="datetime" class="form-control" id="focusedInput" type="text" value="MM/DD/YYYY">
					</h4> </br>

					<h4>Collaborate with others: <h5>
					<select class= "form-control">
						<option value="none">Please Select</option><option value="yes">Yes</option><option value="no">No, not at this time</option>
					</select></h5></h4></br>

					<h4>Tagline:
					<input class="form-control" id="focusedInput" type="text" >
					</h4></br><h6> Example: Beloved mother and wife.</h6>
				</div>
			</div>
			<div id="buttons">
				<button onclick="location.href='create_categories.phtml'"type="button" class="btn btn-primary btn-lg continue">
					Continue
				</button>
				<button onclick="location.href='profile.phtml'"type="button" class="btn btn-primary btn-lg cancel">
					Cancel
				</button>
			</div>
		</div>
		<script src="../Scripts/jquery.min.js"></script>
		<script src="../Scripts/bootstrap.min.js"></script>
		<script src="../Scripts/bootswatch.js"></script>
	</body>
</html>