<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="css/bootstrap.css" media="screen">
		<link rel="stylesheet" href="css/font-awesome.min.css">
		<link rel="stylesheet" href="css/bootswatch.min.css">
		<link rel="stylesheet" href="css/profile_style.css">
		<link rel="stylesheet" href="css/create_memorial.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="js/bsa.js"></script>

				<div class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand" href="profile.phtml"><img src="Images/logo.png"></a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="profile.php">Profile</a>
					</li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div><!-- /.navbar -->


		<div class="jumbotron">
			<h3> Please select the categories from your Facebook account you want Eplilogue to use in creating Grace Pai's Memorial. <br>
				<h4>Note that once you create the memorial, you will not have the option to automatically add or remove anymore of these categories.</h4> 
			</h3><br>
			<form class="category">
			<h3><input type="checkbox">  Posts</input></h3></br>
			<h3><input type="checkbox">  Photos</input></h3></br>
			<h3><input type="checkbox">  Favorites</input></h3></br>
			<h3><input type="checkbox">  Videos</input></h3></br>
			</form>
			

			<button  id="category_continue" onclick="location.href='memorial.php'"type="button" class="btn btn-primary btn-lg continue">
				Create Memorial
			</button>
			<button id="category_cancel" onclick="location.href='profile.php'"type="button" class="btn btn-primary btn-lg cancel">
				Cancel
			</button>
			
		</div>

		<script src="js/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/bootswatch.js"></script>
	</body>
</html>