<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="../Stylesheets/bootstrap.css" media="screen">
		<link rel="stylesheet" href="../Stylesheets/font-awesome.min.css">
		<link rel="stylesheet" href="../Stylesheets/bootswatch.min.css">
		<link rel="stylesheet" href="../Stylesheets/profile_style.css">
		<link rel="stylesheet" href="../Stylesheets/memorial.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="../Scripts/bsa.js"></script>

		<div class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand" href="profile.phtml"><img src="../Images/logo.png"></a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="profile.phtml">Profile</a>
					</li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div><!-- /.navbar -->

		<div class="jumbotron">
			<div id="deceased_info">
				<div id="info_picture"><img src="../Images/profile.jpg">
				</div>
				<div id="info_content">
					<h3>In memory of Grace Yun-Ting Pai</h3>
					<h4>08/28/1992 - 10/26/2013</h4>
					<h4>Beloved sister and friend</h4>
				</div>
			</div>
		</div>
		<hr>

		<div class="jumbotron">
			<div id="coverPicture">
				<span><img src="../Images/collage.jpg"></span>
			</div>
		</div>

		<div class="jumbotron">
			<div class="sections">
				<div class="list-group">
					<a href="section_photos.phtml" class="list-group-item">Photos</a>
					<a href="section_posts.phtml" class="list-group-item">Posts</a>
					<a href="section_favorites.phtml" class="list-group-item">Favorites</a>
					<a href="section_videos.phtml" class="list-group-item">Videos</a>
				</div>
			</div>

			<div class="sections" id="story">
				<ul class="nav nav-tabs" style="margin-bottom: 15px;">
					<li class="active">
						<a href="#Memories" data-toggle="tab">Memories of Grace</a>
					</li>
					<li>
						<a href="#Story" data-toggle="tab">Grace's Story</a>
					</li>
				</ul>
				<div id="myTabContent" class="tab-content">
					<div class="tab-pane fade active in" id="Memories">
						<p> you currently have no stories</p>
					</div>
					<div class="tab-pane fade" id="Story">
						<p> There currently is no story</p>
					</div>
				</div>
			</div>
		</div>
		<hr>

		<script src="../Scripts/jquery.min.js"></script>
		<script src="../Scripts/bootstrap.min.js"></script>
		<script src="../Scripts/bootswatch.js"></script>
	</body>
</html>