<!DOCTYPE html>
<html lang="en">
	<head>
		<title>Epilogue </title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta charset="utf-8">
		<link rel="stylesheet" href="css/bootstrap.css" media="screen">
		<link rel="stylesheet" href="css/font-awesome.min.css">
		<link rel="stylesheet" href="css/bootswatch.min.css">
		<link rel="stylesheet" href="css/profile_style.css">
		<link rel="stylesheet" href="css/style.css">
		<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
		<script src="../bower_components/bootstrap/assets/js/html5shiv.js"></script>
		<script src="../bower_components/bootstrap/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
		<script src="js/bsa.js"></script>

		<div class="navbar navbar-inverse">
			<div class="navbar-header">
				<a class="navbar-brand" href="#"><img src="Images/logo.png"></a>
			</div>
			<div class="navbar-collapse collapse navbar-responsive-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="#">Profile</a>
					</li>
				</ul>
			</div><!-- /.nav-collapse -->
		</div><!-- /.navbar -->

		<div class="bs-example">
			<ul class="nav nav-tabs" style="margin-bottom: 15px;">
				<li class="active">
					<a href="#memorials" data-toggle="tab">Memorials</a>
				</li>
				<li>
					<a href="#invitations" data-toggle="tab">Invitations</a>
				</li>
				<li>
					<a href="#finalizedMemorials" data-toggle="tab">Finalized Memorials</a>
				</li>
			</ul>
			<div id="myTabContent" class="tab-content">
				<?php if($memorialList == null || empty($memorialList)): ?>
				<div class = "tab-pane fade active in" id="memorials">
					<button onclick="location.href='createDeadInfo.php'"type="button" class="btn btn-primary btn-lg">
						Create New Memorial
					</button>
					<h3> you currently have no active memorials</h3>
				</div>
				<?php else: ?>

				<div class="tab-pane fade active in" id="memorials">
					<button onclick="location.href='createDeadInfo.php'"type="button" class="btn btn-primary btn-lg">
						Create New Memorial
					</button>

					<button onclick="location.href='memorial.phtml'" type="button" class="btn btn-default btn-lg btn-block">
						Grace Pai's Memorial
					</button>
					<div class="btn-group btn-group-justified">
						<a href="memorial.phtml" class="btn btn-default">Edit</a>
						<a href="collaborators.phtml" class="btn btn-default">Collaborators</a>
						<a href="finalize_info.phtml" class="btn btn-default">Finalize</a>
						<a href="#" class="btn btn-default">Delete</a>
					</div>

					<button type="button" class="btn btn-default btn-lg btn-block">
						Jane Doe's Memorial
					</button>
					<div class="btn-group btn-group-justified">
						<a href="memorial.phtml" class="btn btn-default">Edit</a>
						<a href="collaborators.phtml" class="btn btn-default">Collaborators</a>
						<a href="finalize_info.phtml" class="btn btn-default">Finalize</a>
						<a href="#" class="btn btn-default">Delete</a>
					</div>
					<!--<center>
					<h2> You currently have no active memorials. </h2>
					</center> -->
				</div>
				<?php endif; ?>
				<div class="tab-pane fade" id="invitations">
					<form id="invitation">
						<div class="bs-example table-responsive">
							<table class="table table-striped table-bordered table-hover">
								<thead>
									<tr>
										<th>Memorial Name</th>
										<th>Accept</th>
										<th>Decline</th>
										<th>Not Now</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td>Grace Pai's Memorial by Marie Gilbert</td>
										<td>
										<input type="checkbox"/>
										</td>
										<td>
										<input type="checkbox"/>
										</td>
										<td>
										<input type="checkbox"/>
										</td>
									</tr>
									<tr>
										<td>Amy Pond's Memorial by River Song</td>
										<td>
										<input type="checkbox"/>
										</td>
										<td>
										<input type="checkbox"/>
										</td>
										<td>
										<input type="checkbox"/>
										</td>
									</tr>
								</tbody>
							</table>
						</div>
					</form>

					<button onclick="location.href='profile.phtml'" type="button" class="btn btn-primary btn-lg" id= "save_button">
						Save
					</button>
				</div>

				<div class="tab-pane fade" id="finalizedMemorials">
					<button onclick="location.href='memorial.phtml'" type="button" class="btn btn-default btn-lg btn-block">
						Rory Williams's Memorial
					</button>
					<div class="btn-group btn-group-justified">
						<a href="#" class="btn btn-default">View</a>
						<a href="#" class="btn btn-default">Download web package</a>
					</div>

				</div>
			</div>
		</div>

		<script src="js/jquery.min.js"></script>
		<script src="js/bootstrap.min.js"></script>
		<script src="js/bootswatch.js"></script>
	</body>
</html>